number1=input('Enter number1')
number2=input("Enter number2")
number3=input("enter nuber3")
print(number1,number2,number3)
sum=int(number1)+int(number2)
print(sum)
difference=int(number1)-int(number2)
print(difference)
mutify=int(number1)*int(number2)
print(mutify)
division=int(number1)/int(number2)
print(division)
print(sum,division,mutify,difference)
sum=int(number1)+int(number2)+int(number3)
print(sum)
difference=int(number1)-int(number2)-int(number3)
print(difference)
mutify=int(number1)*int(number2)*int(number3)
print(mutify)
division=int(number1)/int(number2)/int(number2)
print(division)
print(sum,division,mutify,difference)
import math
print(math.pow(9,3))
