number1=input('Enter number1')
number2=input("Enter number2")
number3=input("Enter nuber3")
print(number1,number2,number3)
sum=int(number1)+int(number2)
print(sum)
difference=int(number1)-int(number2)
print(difference)
mutify=int(number1)*int(number2)
print(mutify)
division=int(number1)/int(number2)
print(division)
print(sum,division,mutify,difference)
sum=int(number1)+int(number2)+int(number3)
print(sum)
difference=int(number1)-int(number2)-int(number3)
print(difference)
mutify=int(number1)*int(number2)*int(number3)
print(mutify)
division=int(number1)/int(number2)/int(number2)
print(division)
print(sum,division,mutify,difference)
import math
print(math.pow(9,3))
x=math.ceil(6.1)
print (x)
x=math.sqrt(66)
print(x)
y=math.floor(6.9)
print(y)
x=math.log10(4.5)
print(x)
y=math.pi
print(y)
x=math.fabs(7.4)
print(x)
x=math.sin(5.3)
print(x)
x=math.log2(10)
print(x)
y=math.factorial(25)
print(y)
